import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  Alert,
  ActivityIndicator,
} from 'react-native';
import { router } from 'expo-router';
import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';
import { Colors, Spacing, FontSize, BorderRadius } from '../constants/theme';
import { format, subDays, startOfWeek, endOfWeek } from 'date-fns';

export default function ReportScreen() {
  const { user } = useAuth();
  const [loading, setLoading] = useState(false);
  const [reportType, setReportType] = useState<'weekly' | 'monthly' | 'all'>('weekly');

  const generateReport = async () => {
    if (!user) return;
    setLoading(true);

    try {
      // Fetch profile
      const { data: profile } = await supabase
        .from('profiles')
        .select('full_name')
        .eq('id', user.id)
        .single();

      // Fetch all habits
      const { data: habits } = await supabase
        .from('habits')
        .select('*')
        .eq('user_id', user.id);

      // Determine date range
      let startDate: Date;
      let endDate = new Date();
      let rangeLabel = '';

      if (reportType === 'weekly') {
        startDate = startOfWeek(new Date(), { weekStartsOn: 1 });
        endDate = endOfWeek(new Date(), { weekStartsOn: 1 });
        rangeLabel = `${format(startDate, 'MMM d')} – ${format(endDate, 'MMM d, yyyy')}`;
      } else if (reportType === 'monthly') {
        startDate = subDays(new Date(), 30);
        rangeLabel = `Last 30 days (${format(startDate, 'MMM d')} – ${format(endDate, 'MMM d, yyyy')})`;
      } else {
        startDate = subDays(new Date(), 365);
        rangeLabel = `All time up to ${format(endDate, 'MMM d, yyyy')}`;
      }

      // Fetch logs for range
      const { data: logs } = await supabase
        .from('habit_logs')
        .select('*')
        .eq('user_id', user.id)
        .gte('completed_at', startDate.toISOString())
        .lte('completed_at', endDate.toISOString())
        .order('completed_at', { ascending: false });

      // Build habit rows
      const habitRows = await Promise.all(
        (habits || []).map(async (habit) => {
          const habitLogs = (logs || []).filter((l) => l.habit_id === habit.id);
          const days = reportType === 'weekly' ? 7 : reportType === 'monthly' ? 30 : 365;
          const rate = Math.round((habitLogs.length / days) * 100);

          // Streak
          const { data: allLogs } = await supabase
            .from('habit_logs')
            .select('completed_at')
            .eq('habit_id', habit.id)
            .eq('user_id', user.id)
            .order('completed_at', { ascending: false })
            .limit(30);

          let streak = 0;
          let checkDate = new Date();
          for (let i = 0; i < 30; i++) {
            const ds = format(checkDate, 'yyyy-MM-dd');
            if ((allLogs || []).some((l) => l.completed_at.startsWith(ds))) {
              streak++;
              checkDate.setDate(checkDate.getDate() - 1);
            } else break;
          }

          return {
            name: `${habit.icon} ${habit.name}`,
            completions: habitLogs.length,
            rate,
            streak,
            frequency: habit.frequency,
          };
        })
      );

      const totalLogs = logs?.length || 0;
      const totalHabits = habits?.length || 0;
      const avgPerDay = totalLogs > 0 ? (totalLogs / (reportType === 'weekly' ? 7 : reportType === 'monthly' ? 30 : 365)).toFixed(1) : '0';
      const topHabit = habits?.reduce((top, h) => {
        const count = (logs || []).filter((l) => l.habit_id === h.id).length;
        return count > top.count ? { name: `${h.icon} ${h.name}`, count } : top;
      }, { name: 'None', count: 0 });

      // Generate plain-text report
      const generatedOn = format(new Date(), 'MMMM d, yyyy \u00b7 h:mm a');
      const reportId = `HF-${Date.now()}-${user.id.slice(0, 8).toUpperCase()}`;
      const line = '-'.repeat(40);

      const habitLines = habitRows.map((h) =>
        `\u2022 ${h.name}\n    Completions: ${h.completions}   Rate: ${h.rate}%   Streak: \ud83d\udd25 ${h.streak}   Schedule: ${h.frequency}`
      ).join('\n\n');

      const reportText = [
        'HABITTRACKER \u2014 ACTIVITY REPORT',
        line,
        '',
        `Generated On: ${generatedOn}`,
        `Report Period: ${rangeLabel}`,
        '',
        '\u2713 Verified Activity Log \u2014 Auto-generated by HabitTracker',
        '',
        `User: ${profile?.full_name || 'User'}`,
        `Email: ${user.email}`,
        '',
        'SUMMARY',
        line,
        `Active Habits: ${totalHabits}`,
        `Total Completions: ${totalLogs}`,
        `Avg Per Day: ${avgPerDay}`,
        `Top Habit: ${topHabit?.name || '\u2014'}`,
        '',
        'HABIT PERFORMANCE',
        line,
        habitLines || 'No habits tracked yet.',
        '',
        line,
        `Report ID: ${reportId}`,
        `\u00a9 ${new Date().getFullYear()} HabitTracker \u2014 All data is user-generated and verified against Supabase records.`,
      ].join('\n');

      const fileName = `HabitTracker_Report_${Date.now()}.txt`;
      const file = new File(Paths.cache, fileName);
      file.write(reportText);

      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(file.uri, {
          mimeType: 'text/plain',
          dialogTitle: 'Share your HabitTracker Report',
        });
      } else {
        Alert.alert('Report Generated', `Saved to: ${file.uri}`);
      }
    } catch (err) {
      console.error('Report error:', err);
      Alert.alert('Error', 'Could not generate report. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <Text style={styles.backBtnText}>✕</Text>
        </TouchableOpacity>
        <Text style={styles.title}>Activity Report</Text>
        <View style={{ width: 36 }} />
      </View>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <View style={styles.iconBanner}>
          <Text style={styles.iconBannerEmoji}>📄</Text>
          <Text style={styles.iconBannerTitle}>Generate Your Report</Text>
          <Text style={styles.iconBannerSub}>
            Export a verified text activity log with habit performance, streaks, and completion rates.
          </Text>
        </View>

        {/* Report type selector */}
        <Text style={styles.sectionLabel}>Report Period</Text>
        {[
          { label: 'This Week', sub: 'Mon – Sun of current week', value: 'weekly' as const },
          { label: 'Last 30 Days', sub: 'Rolling 30-day window', value: 'monthly' as const },
          { label: 'All Time', sub: 'Complete history up to today', value: 'all' as const },
        ].map((option) => (
          <TouchableOpacity
            key={option.value}
            style={[styles.typeOption, reportType === option.value && styles.typeOptionSelected]}
            onPress={() => setReportType(option.value)}
          >
            <View style={styles.typeRadio}>
              {reportType === option.value && <View style={styles.typeRadioDot} />}
            </View>
            <View style={styles.typeInfo}>
              <Text style={[styles.typeLabel, reportType === option.value && styles.typeLabelSelected]}>
                {option.label}
              </Text>
              <Text style={styles.typeSub}>{option.sub}</Text>
            </View>
          </TouchableOpacity>
        ))}

        {/* What's included */}
        <View style={styles.includesCard}>
          <Text style={styles.includesTitle}>What's included</Text>
          {[
            '✅ User profile & account info',
            '📊 Habit performance table',
            '🔥 Current streaks per habit',
            '📈 Completion rates & averages',
            '🏷️ Unique report ID for verification',
            '📅 Report generation timestamp',
          ].map((item, i) => (
            <Text key={i} style={styles.includeItem}>{item}</Text>
          ))}
        </View>

        <TouchableOpacity
          style={[styles.generateBtn, loading && styles.generateBtnDisabled]}
          onPress={generateReport}
          disabled={loading}
        >
          {loading ? (
            <View style={styles.generateBtnInner}>
              <ActivityIndicator color={Colors.background} />
              <Text style={styles.generateBtnText}>Generating Report...</Text>
            </View>
          ) : (
            <Text style={styles.generateBtnText}>📥 Download Text Report</Text>
          )}
        </TouchableOpacity>

        <View style={styles.bottomSpacer} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    paddingTop: 56,
    paddingBottom: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.surfaceLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backBtnText: {
    color: Colors.textSecondary,
    fontSize: FontSize.md,
  },
  title: {
    fontSize: FontSize.xl,
    fontWeight: '800',
    color: Colors.text,
  },
  content: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.xl,
    paddingBottom: 60,
  },
  iconBanner: {
    alignItems: 'center',
    marginBottom: Spacing.xl,
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.xl,
    padding: Spacing.xl,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  iconBannerEmoji: {
    fontSize: 48,
    marginBottom: Spacing.md,
  },
  iconBannerTitle: {
    fontSize: FontSize.xl,
    fontWeight: '800',
    color: Colors.text,
    marginBottom: Spacing.sm,
  },
  iconBannerSub: {
    fontSize: FontSize.md,
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
  },
  sectionLabel: {
    fontSize: FontSize.sm,
    fontWeight: '700',
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: Spacing.md,
  },
  typeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  typeOptionSelected: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + '10',
  },
  typeRadio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Spacing.md,
  },
  typeRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.primary,
  },
  typeInfo: {
    flex: 1,
  },
  typeLabel: {
    fontSize: FontSize.md,
    fontWeight: '600',
    color: Colors.textSecondary,
  },
  typeLabelSelected: {
    color: Colors.text,
  },
  typeSub: {
    fontSize: FontSize.sm,
    color: Colors.textMuted,
    marginTop: 2,
  },
  includesCard: {
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    marginTop: Spacing.lg,
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  includesTitle: {
    fontSize: FontSize.md,
    fontWeight: '700',
    color: Colors.text,
    marginBottom: Spacing.md,
  },
  includeItem: {
    fontSize: FontSize.md,
    color: Colors.textSecondary,
    marginBottom: Spacing.sm,
    lineHeight: 22,
  },
  generateBtn: {
    backgroundColor: Colors.primary,
    borderRadius: BorderRadius.lg,
    paddingVertical: Spacing.md,
    alignItems: 'center',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  generateBtnDisabled: {
    opacity: 0.7,
  },
  generateBtnInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  generateBtnText: {
    color: Colors.white,
    fontSize: FontSize.md,
    fontWeight: '700',
  },
  bottomSpacer: {
    height: 40,
  },
});